### ISSUE TITLE
music_dir not found, 

### ISSUE THREAD

**Issue by eater** [mavit/slimpris2#8]
In my slimpris2.conf I have my host and port and `music_dir = /mnt/media` which is indeed where all the music lives, but when I start slimpris2 it says

```
2020-12-16 11:50:07,904 slimpris2 WARNING: Music library path: [Errno 2] No such file or directory: '/mnt/media'
2020-12-16 11:50:07,904 slimpris2 WARNING: By not supplying a path for the music library this program will break the MPRIS specification!
```
Not sure if that's why this fails too:
```
$ playerctl --player=squeezebox status
No player could handle this command
```

**Comment by mavit** [comment]
> In my slimpris2.conf I have my host and port and `music_dir = /mnt/media` which is indeed where all the music lives, but when I start slimpris2 it says
> 
> ```
> 2020-12-16 11:50:07,904 slimpris2 WARNING: Music library path: [Errno 2] No such file or directory: '/mnt/media'
> 2020-12-16 11:50:07,904 slimpris2 WARNING: By not supplying a path for the music library this program will break the MPRIS specification!
> ```

What does the command `ls -l /mnt/media` say on the host where you're running `slimpris2`?

> Not sure if that's why this fails too:
> 
> ```
> $ playerctl --player=squeezebox status
> No player could handle this command
> ```

I set `music_dir` to a non-existent directory and this command worked as expected for me, so I think this could be a separate issue.

**Comment by eater** [comment]
When I ssh to the squeezebox server, `ls -l /mnt/media` displays the long list of music directories in that folder.

You're right about the "No player could handle this" issue, that went away on its own and everything's working, but the `music_dir` warning is still there.

**Comment by mavit** [comment]
Confusingly, `music_dir` is expected to be a directory that holds your music *from the point of view of `slimpris2`*, not LMS.  Since these are quite likely to be on different hosts, this may well be impossible.

Digging into the code, though, it turns out that `music_dir` is never actually used.  I guess the original author of `slimpris2` intended to use it to map the URL provided by LMS to one that was accessible on the client, but never got around to implementing this feature.

I have removed the option.  Thanks for the report.

**Comment by eater** [comment]
Thanks!
